name: Compile pfSense packages

on:
    push:
      branches:
        - main

jobs:
  build:
    name: pfSense Package Builder
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up pfSense build environment
        uses: vmactions/freebsd-vm@1
        with:
          usesh: true
          prepare: |
            pkg update
            pkg install -y git
            pkg install -y poudriere
          run: |
            pwd
            ls -la
