name: Compile pfSense packages

on:
  workflow_dispatch:

jobs:
  build:
    name: pfSense Package Builder
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Set up pfSense build environment
      id: pfsense
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y git
          pkg install -y poudriere
        run: |
          freebsd-version
